### PR TITLE
fixes for SS 3.5 (possibly 3.2+?)

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by UndefinedOffset** [comment]
Sorry for the delay on reviewing and merging this very busy here at WBG :). I hope to hit this in the coming weeks as we're about to use it on a project.

**Comment by xini** [comment]
Hi Ed,
No problem. I just used it again for another project and I think it will need some more tweaking on top of this. When I have time I'll add some more changes...
Cheers, Flo

**Comment by UndefinedOffset** [comment]
Looks good merged, thanks :)

**Comment by xini** [comment]
no problem. can you please tag a release with this when ready?

**Comment by UndefinedOffset** [comment]
done thanks again, and sorry for the long turn around busy times ;)

**Comment by xini** [comment]
thanks!

**Pull request merged**
